parameters:
#    enjoy_crawler.example.class: Enjoy\CrawlerBundle\Example

services:
#    enjoy_crawler.example:
#        class: %enjoy_crawler.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
