Enjoy\MainBundle\Entity\Crowled:
    type: entity
    table: crowled
    manyToOne:
        facility:
          targetEntity: Facility
          joinColumn:
            name: facility_id
            referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
