Enjoy\MainBundle\Entity\MovieDate:
    type: entity
    table: movie_date
    manyToOne:
        movie:
          targetEntity: Movie
          inversedBy: dates
          joinColumn:
            name: movie_id
            referencedColumnName: id
        facility:
          targetEntity: Facility
          joinColumn:
            name: facility_id
            referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
        d_type:
            type: integer
        l_type:
            type: integer

